#!/usr/bin/env python3
"""Evaluate real and synthetic BTC/ETH paths generated by the conditional Normalizing Flow.

The script compares validation data only. It does not use the test split.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(
            "results/normalizing_flow_60epochs/validation_synthetic_paths.npz"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/normalizing_flow_evaluation"),
    )
    parser.add_argument("--portfolio-value", type=float, default=100_000.0)
    parser.add_argument("--btc-weight", type=float, default=0.60)
    parser.add_argument("--eth-weight", type=float, default=0.40)
    return parser.parse_args()


def skewness(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=np.float64)
    std = x.std(ddof=0)
    if std == 0:
        return 0.0
    return float(np.mean(((x - x.mean()) / std) ** 3))


def excess_kurtosis(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=np.float64)
    std = x.std(ddof=0)
    if std == 0:
        return 0.0
    return float(np.mean(((x - x.mean()) / std) ** 4) - 3.0)


def wasserstein_equal_size(a: np.ndarray, b: np.ndarray) -> float:
    a = np.sort(np.asarray(a, dtype=np.float64).ravel())
    b = np.sort(np.asarray(b, dtype=np.float64).ravel())
    if len(a) == len(b):
        return float(np.mean(np.abs(a - b)))

    q = np.linspace(0.0, 1.0, max(len(a), len(b)))
    qa = np.quantile(a, q)
    qb = np.quantile(b, q)
    return float(np.mean(np.abs(qa - qb)))


def describe(x: np.ndarray) -> dict[str, float]:
    x = np.asarray(x, dtype=np.float64).ravel()
    return {
        "mean": float(x.mean()),
        "std": float(x.std(ddof=1)),
        "skewness": skewness(x),
        "excess_kurtosis": excess_kurtosis(x),
        "q01": float(np.quantile(x, 0.01)),
        "q05": float(np.quantile(x, 0.05)),
        "q50": float(np.quantile(x, 0.50)),
        "q95": float(np.quantile(x, 0.95)),
        "q99": float(np.quantile(x, 0.99)),
    }


def path_correlations(paths: np.ndarray) -> np.ndarray:
    values = []
    for path in paths:
        btc = path[:, 0]
        eth = path[:, 1]
        if btc.std() == 0 or eth.std() == 0:
            values.append(0.0)
        else:
            values.append(float(np.corrcoef(btc, eth)[0, 1]))
    return np.asarray(values, dtype=np.float64)


def portfolio_statistics(
    paths: np.ndarray,
    initial_value: float,
    btc_weight: float,
    eth_weight: float,
) -> dict[str, np.ndarray]:
    cumulative_log_returns = np.cumsum(paths, axis=1)
    gross_prices = np.exp(cumulative_log_returns)

    portfolio = initial_value * (
        btc_weight * gross_prices[:, :, 0]
        + eth_weight * gross_prices[:, :, 1]
    )

    initial_column = np.full((len(paths), 1), initial_value, dtype=np.float64)
    portfolio_with_initial = np.concatenate([initial_column, portfolio], axis=1)

    running_max = np.maximum.accumulate(portfolio_with_initial, axis=1)
    drawdowns = portfolio_with_initial / running_max - 1.0

    final_return = portfolio_with_initial[:, -1] / initial_value - 1.0
    max_drawdown = drawdowns.min(axis=1)
    loss = -final_return

    return {
        "portfolio_paths": portfolio_with_initial,
        "final_return": final_return,
        "max_drawdown": max_drawdown,
        "loss": loss,
    }


def var_es(losses: np.ndarray, confidence: float) -> tuple[float, float]:
    var = float(np.quantile(losses, confidence))
    tail = losses[losses >= var]
    es = float(tail.mean()) if len(tail) else var
    return var, es


def nearest_real_rmse(
    synthetic: np.ndarray,
    real: np.ndarray,
    chunk_size: int = 64,
) -> np.ndarray:
    syn = synthetic.reshape(len(synthetic), -1).astype(np.float64)
    ref = real.reshape(len(real), -1).astype(np.float64)
    result = np.empty(len(syn), dtype=np.float64)

    for start in range(0, len(syn), chunk_size):
        stop = min(start + chunk_size, len(syn))
        chunk = syn[start:stop]
        # [chunk, real, dimensions]
        squared = (chunk[:, None, :] - ref[None, :, :]) ** 2
        mse = squared.mean(axis=2)
        result[start:stop] = np.sqrt(mse.min(axis=1))
    return result


def save_histogram(
    real_values: np.ndarray,
    synthetic_values: np.ndarray,
    title: str,
    xlabel: str,
    output_path: Path,
) -> None:
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(real_values, bins=50, alpha=0.55, density=True, label="Real")
    ax.hist(synthetic_values, bins=50, alpha=0.55, density=True, label="Synthetic")
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Density")
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_path, dpi=170)
    plt.close(fig)


def save_training_curve_if_present(input_path: Path, output_dir: Path) -> None:
    history_path = input_path.parent / "training_history.csv"
    if not history_path.exists():
        return

    data = np.genfromtxt(history_path, delimiter=",", names=True)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(data["epoch"], data["train_nll_per_dimension"], label="Train")
    ax.plot(data["epoch"], data["validation_nll_per_dimension"], label="Validation")
    best_idx = int(np.argmin(data["validation_nll_per_dimension"]))
    best_epoch = int(data["epoch"][best_idx])
    ax.axvline(best_epoch, linestyle="--", label=f"Best epoch: {best_epoch}")
    ax.set_title("Conditional RealNVP training")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("NLL per dimension")
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_dir / "01_training_curve.png", dpi=170)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if not args.input.exists():
        raise FileNotFoundError(f"Input file not found: {args.input}")

    if not np.isclose(args.btc_weight + args.eth_weight, 1.0):
        raise ValueError("Portfolio weights must add up to 1.")

    with np.load(args.input, allow_pickle=False) as data:
        real = data["real_returns"].astype(np.float64)
        synthetic = data["generated_returns"].astype(np.float64)
        assets = [str(x) for x in data["assets"]]

    if real.shape != synthetic.shape:
        raise ValueError(
            f"Real and synthetic arrays must have the same shape: "
            f"{real.shape} != {synthetic.shape}"
        )
    if real.ndim != 3 or real.shape[2] != 2:
        raise ValueError(f"Expected [paths, steps, 2 assets], got {real.shape}")

    save_training_curve_if_present(args.input, args.output_dir)

    real_cumulative = real.sum(axis=1)
    synthetic_cumulative = synthetic.sum(axis=1)
    real_volatility = real.std(axis=1, ddof=1)
    synthetic_volatility = synthetic.std(axis=1, ddof=1)
    real_corr = path_correlations(real)
    synthetic_corr = path_correlations(synthetic)

    real_portfolio = portfolio_statistics(
        real, args.portfolio_value, args.btc_weight, args.eth_weight
    )
    synthetic_portfolio = portfolio_statistics(
        synthetic, args.portfolio_value, args.btc_weight, args.eth_weight
    )

    nearest_rmse = nearest_real_rmse(synthetic, real)
    rounded_flat = np.round(synthetic.reshape(len(synthetic), -1), decimals=8)
    unique_ratio = float(np.unique(rounded_flat, axis=0).shape[0] / len(synthetic))

    metrics: dict[str, object] = {
        "scope": "validation_only",
        "input_file": str(args.input),
        "n_paths": int(len(real)),
        "steps_per_path": int(real.shape[1]),
        "assets": assets,
        "portfolio": {
            "initial_value": args.portfolio_value,
            "btc_weight": args.btc_weight,
            "eth_weight": args.eth_weight,
        },
        "point_returns": {},
        "cumulative_30d_log_returns": {},
        "path_volatility_6h": {},
        "path_correlation_btc_eth": {
            "real": describe(real_corr),
            "synthetic": describe(synthetic_corr),
            "wasserstein_distance": wasserstein_equal_size(real_corr, synthetic_corr),
        },
        "portfolio_final_return": {
            "real": describe(real_portfolio["final_return"]),
            "synthetic": describe(synthetic_portfolio["final_return"]),
            "wasserstein_distance": wasserstein_equal_size(
                real_portfolio["final_return"],
                synthetic_portfolio["final_return"],
            ),
        },
        "portfolio_max_drawdown": {
            "real": describe(real_portfolio["max_drawdown"]),
            "synthetic": describe(synthetic_portfolio["max_drawdown"]),
            "wasserstein_distance": wasserstein_equal_size(
                real_portfolio["max_drawdown"],
                synthetic_portfolio["max_drawdown"],
            ),
        },
        "portfolio_risk": {},
        "diversity_and_memorization": {
            "unique_synthetic_ratio_rounded_8_decimals": unique_ratio,
            "nearest_real_path_rmse": describe(nearest_rmse),
        },
    }

    for index, asset in enumerate(assets):
        metrics["point_returns"][asset] = {
            "real": describe(real[:, :, index]),
            "synthetic": describe(synthetic[:, :, index]),
            "wasserstein_distance": wasserstein_equal_size(
                real[:, :, index], synthetic[:, :, index]
            ),
        }
        metrics["cumulative_30d_log_returns"][asset] = {
            "real": describe(real_cumulative[:, index]),
            "synthetic": describe(synthetic_cumulative[:, index]),
            "wasserstein_distance": wasserstein_equal_size(
                real_cumulative[:, index], synthetic_cumulative[:, index]
            ),
        }
        metrics["path_volatility_6h"][asset] = {
            "real": describe(real_volatility[:, index]),
            "synthetic": describe(synthetic_volatility[:, index]),
            "wasserstein_distance": wasserstein_equal_size(
                real_volatility[:, index], synthetic_volatility[:, index]
            ),
        }

    for confidence in (0.95, 0.99):
        real_var, real_es = var_es(real_portfolio["loss"], confidence)
        synthetic_var, synthetic_es = var_es(
            synthetic_portfolio["loss"], confidence
        )
        key = f"{int(confidence * 100)}pct"
        metrics["portfolio_risk"][key] = {
            "real_var": real_var,
            "real_expected_shortfall": real_es,
            "synthetic_var": synthetic_var,
            "synthetic_expected_shortfall": synthetic_es,
        }

    (args.output_dir / "evaluation_metrics.json").write_text(
        json.dumps(metrics, indent=2), encoding="utf-8"
    )

    rows: list[dict[str, object]] = []
    for section in (
        "point_returns",
        "cumulative_30d_log_returns",
        "path_volatility_6h",
    ):
        for asset, values in metrics[section].items():
            for statistic in (
                "mean",
                "std",
                "skewness",
                "excess_kurtosis",
                "q01",
                "q05",
                "q50",
                "q95",
                "q99",
            ):
                rows.append(
                    {
                        "section": section,
                        "asset": asset,
                        "statistic": statistic,
                        "real": values["real"][statistic],
                        "synthetic": values["synthetic"][statistic],
                        "absolute_difference": abs(
                            values["real"][statistic]
                            - values["synthetic"][statistic]
                        ),
                    }
                )

    with (args.output_dir / "evaluation_table.csv").open(
        "w", newline="", encoding="utf-8"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    save_histogram(
        real_cumulative[:, 0],
        synthetic_cumulative[:, 0],
        "BTC cumulative 30-day log return",
        "Cumulative log return",
        args.output_dir / "02_btc_cumulative_return.png",
    )
    save_histogram(
        real_cumulative[:, 1],
        synthetic_cumulative[:, 1],
        "ETH cumulative 30-day log return",
        "Cumulative log return",
        args.output_dir / "03_eth_cumulative_return.png",
    )
    save_histogram(
        real_corr,
        synthetic_corr,
        "BTC–ETH correlation by 30-day path",
        "Correlation",
        args.output_dir / "04_path_correlation.png",
    )
    save_histogram(
        real_portfolio["final_return"],
        synthetic_portfolio["final_return"],
        "Portfolio 60/40 final return",
        "Final return",
        args.output_dir / "05_portfolio_final_return.png",
    )
    save_histogram(
        real_portfolio["max_drawdown"],
        synthetic_portfolio["max_drawdown"],
        "Portfolio 60/40 maximum drawdown",
        "Maximum drawdown",
        args.output_dir / "06_portfolio_max_drawdown.png",
    )

    print("\nNORMALIZING FLOW — COMPLETE VALIDATION EVALUATION")
    print("=" * 62)
    print(f"Paths compared: {len(real)}")
    print(f"Shape per path: {real.shape[1]} steps x {real.shape[2]} assets")
    print("\nPortfolio 60/40 risk")
    for confidence in (0.95, 0.99):
        key = f"{int(confidence * 100)}pct"
        values = metrics["portfolio_risk"][key]
        print(
            f"VaR {int(confidence * 100)}% | "
            f"real={values['real_var']:.2%} "
            f"synthetic={values['synthetic_var']:.2%}"
        )
        print(
            f"ES  {int(confidence * 100)}% | "
            f"real={values['real_expected_shortfall']:.2%} "
            f"synthetic={values['synthetic_expected_shortfall']:.2%}"
        )

    print("\nPortfolio maximum drawdown")
    print(
        "Mean | "
        f"real={metrics['portfolio_max_drawdown']['real']['mean']:.2%} "
        f"synthetic={metrics['portfolio_max_drawdown']['synthetic']['mean']:.2%}"
    )
    print(
        "1% worst quantile | "
        f"real={metrics['portfolio_max_drawdown']['real']['q01']:.2%} "
        f"synthetic={metrics['portfolio_max_drawdown']['synthetic']['q01']:.2%}"
    )

    print("\nDiversity")
    print(f"Unique synthetic ratio: {unique_ratio:.2%}")
    print(
        "Median nearest-real path RMSE: "
        f"{metrics['diversity_and_memorization']['nearest_real_path_rmse']['q50']:.6f}"
    )

    print(f"\nSaved metrics and figures in: {args.output_dir}")


if __name__ == "__main__":
    main()
